package com.echoflow.core.safety

import com.echoflow.core.gateway.BlockReason
import com.echoflow.core.gateway.GateContext
import com.echoflow.core.gateway.PlannedAction
import com.echoflow.core.model.ScreenSnapshot
import java.util.concurrent.CopyOnWriteArrayList
import java.util.concurrent.atomic.AtomicReference

sealed interface GateDecision {
    data class Allow(val risk: ActionRisk) : GateDecision

    data class Block(
        val reason: BlockReason,
        val detail: String,
        /** Non-null when the block is also a hand-off to the user. */
        val handOff: SensitiveKind? = null,
    ) : GateDecision
}

data class Trip(
    val kind: SensitiveKind,
    val detail: String,
    val snapshotId: Long,
    val packageName: String?,
    val atMs: Long,
) {
    /** The fixed hand-off line. Never generated by an LLM. */
    val handOffMessage: String
        get() = when (kind) {
            SensitiveKind.LOGIN -> "This looks like a login screen, so I've stopped. Please log in yourself, then say continue."
            SensitiveKind.OPAQUE_UNKNOWN -> "I can't read this screen, so I've stopped to be safe. Please take over."
            else -> "This is ${kind.spoken}. I've stopped. Please complete it yourself."
        }
}

sealed interface GuardState {
    data object Armed : GuardState
    data class Tripped(val trip: Trip) : GuardState
}

sealed interface ResumeResult {
    data object Resumed : ResumeResult
    data object NotTripped : ResumeResult
    data object NeedsUserConfirmation : ResumeResult
    data class StillSensitive(val verdict: ScreenVerdict) : ResumeResult
}

/**
 * The credential/payment safety net. Two roles:
 *  - watcher: [onSnapshot] runs on every captured screen and trips on anything sensitive;
 *  - gate: [gate] runs synchronously before every action.
 * Once tripped it stays tripped until the user explicitly resumes on a non-sensitive screen.
 * Deterministic and local by design: no LLM output can change its decisions.
 */
class SafetyGuard(
    private val screenClassifier: ScreenSafetyClassifier = ScreenSafetyClassifier(),
    private val actionClassifier: ActionRiskClassifier = ActionRiskClassifier(),
    private val clock: () -> Long = System::currentTimeMillis,
) {
    private val state = AtomicReference<GuardState>(GuardState.Armed)
    private val tripListeners = CopyOnWriteArrayList<(Trip) -> Unit>()

    @Volatile
    var lastVerdict: ScreenVerdict? = null
        private set

    val currentState: GuardState get() = state.get()
    val isTripped: Boolean get() = state.get() is GuardState.Tripped

    fun addTripListener(listener: (Trip) -> Unit) {
        tripListeners += listener
    }

    fun removeTripListener(listener: (Trip) -> Unit) {
        tripListeners -= listener
    }

    fun classify(snapshot: ScreenSnapshot): ScreenVerdict = screenClassifier.classify(snapshot)

    /** Watcher entry point. Returns the verdict and trips if the screen is sensitive. */
    fun onSnapshot(snapshot: ScreenSnapshot): ScreenVerdict {
        val verdict = screenClassifier.classify(snapshot)
        lastVerdict = verdict
        verdict.primaryKind?.let { trip(it, verdict.summary(), snapshot) }
        return verdict
    }

    fun gate(action: PlannedAction, snapshot: ScreenSnapshot, context: GateContext): GateDecision {
        (state.get() as? GuardState.Tripped)?.let {
            return GateDecision.Block(BlockReason.GUARD_TRIPPED, "handed off: ${it.trip.kind}", it.trip.kind)
        }

        val verdict = onSnapshot(snapshot)
        verdict.primaryKind?.let {
            return GateDecision.Block(BlockReason.SENSITIVE_SCREEN, verdict.summary(), it)
        }

        return when (action) {
            is PlannedAction.Back -> GateDecision.Allow(ActionRisk.SAFE)
            is PlannedAction.LaunchApp -> gateLaunch(action, snapshot)
            is PlannedAction.Targeted -> gateTargeted(action, snapshot, context)
        }
    }

    private fun gateLaunch(action: PlannedAction.LaunchApp, snapshot: ScreenSnapshot): GateDecision {
        val probe = snapshot.copy(packageName = action.packageName, windows = emptyList(), elements = emptyList())
        val pkgSignal = screenClassifier.classify(probe).signals
            .firstOrNull { it.rule == "payment-app" || (it.rule == "login-app" && it.strength == SignalStrength.STRONG) }
        return if (pkgSignal != null) {
            GateDecision.Block(BlockReason.SENSITIVE_PACKAGE, pkgSignal.evidence)
        } else {
            GateDecision.Allow(ActionRisk.SAFE)
        }
    }

    private fun gateTargeted(action: PlannedAction.Targeted, snapshot: ScreenSnapshot, context: GateContext): GateDecision {
        if (action.snapshotId != snapshot.id) {
            return GateDecision.Block(BlockReason.STALE_SNAPSHOT, "resolved on ${action.snapshotId}, screen is ${snapshot.id}")
        }
        val target = snapshot.elements.getOrNull(action.elementIndex)
            ?: return GateDecision.Block(BlockReason.UNKNOWN_TARGET, "no element ${action.elementIndex}")

        if (action is PlannedAction.SetText || action is PlannedAction.ImeEnter) {
            // The screen verdict above already covers password/OTP/card fields; this re-checks the
            // single field in case the rest of the screen looked harmless.
            val fieldOnly = snapshot.copy(elements = listOf(target.copy(index = 0, parent = -1)), windows = emptyList())
            val fieldVerdict = screenClassifier.classify(fieldOnly)
            val fieldKind = fieldVerdict.kinds.firstOrNull { it != SensitiveKind.OPAQUE_UNKNOWN }
            if (fieldKind != null) {
                trip(fieldKind, "typing into a ${fieldKind.name.lowercase()} field", snapshot)
                return GateDecision.Block(BlockReason.SENSITIVE_FIELD, fieldVerdict.summary(), fieldKind)
            }
            return GateDecision.Allow(ActionRisk.SAFE)
        }

        if (action is PlannedAction.Scroll) return GateDecision.Allow(ActionRisk.SAFE)

        val assessment = actionClassifier.assess(snapshot, target)
        return when (assessment.risk) {
            ActionRisk.COMMIT -> {
                trip(SensitiveKind.PAYMENT, "commit action: ${assessment.evidence}", snapshot)
                GateDecision.Block(BlockReason.COMMIT_ACTION, "commit action: ${assessment.evidence}", SensitiveKind.PAYMENT)
            }
            ActionRisk.DESTRUCTIVE -> when {
                context.isRecovery ->
                    GateDecision.Block(BlockReason.DESTRUCTIVE_ACTION, "recovery may not '${assessment.evidence}'")
                !context.explicitlyTaught || context.resolverConfidence < DESTRUCTIVE_MIN_CONFIDENCE ->
                    GateDecision.Block(BlockReason.DESTRUCTIVE_ACTION, "'${assessment.evidence}' needs a taught step and confidence ≥ $DESTRUCTIVE_MIN_CONFIDENCE")
                else -> GateDecision.Allow(ActionRisk.DESTRUCTIVE)
            }
            ActionRisk.NAVIGATES_TO_PAYMENT, ActionRisk.SAFE -> GateDecision.Allow(assessment.risk)
        }
    }

    /**
     * Re-arms after a hand-off. Requires an explicit user confirmation ("continue") *and* that
     * the current screen is no longer sensitive.
     */
    fun resume(current: ScreenSnapshot, userConfirmed: Boolean): ResumeResult {
        if (state.get() !is GuardState.Tripped) return ResumeResult.NotTripped
        if (!userConfirmed) return ResumeResult.NeedsUserConfirmation
        val verdict = screenClassifier.classify(current)
        lastVerdict = verdict
        if (verdict.isSensitive) return ResumeResult.StillSensitive(verdict)
        state.set(GuardState.Armed)
        return ResumeResult.Resumed
    }

    private fun trip(kind: SensitiveKind, detail: String, snapshot: ScreenSnapshot) {
        val trip = Trip(kind, detail, snapshot.id, snapshot.packageName, clock())
        // Only the first trip notifies; later sensitive screens keep the original hand-off.
        if (state.compareAndSet(GuardState.Armed, GuardState.Tripped(trip))) {
            tripListeners.forEach { runCatching { it(trip) } }
        }
    }

    companion object {
        const val DESTRUCTIVE_MIN_CONFIDENCE = 0.9
    }
}
